./"This is man page for EnDeZip script.
.TH EnDeZip 1 "19.04.2017" "Version 1.1" "EnDeZip man page"

.SH NAME
EnDeZip

.SH DESCRIPTION
This script is supposed to compress and decompress files using popular programs. Besides it also has encripting and decripting feature, which protects files with password.

.SH OPTIONS
.IP -h
displays help
.IP -v
dispalys header with informations about version, author, license etc. 

\fB\WITHOUT OPTIONS\fR 
Turn on program with Zenity interface 

.SH AUTHOR
Tomasz Kiełczewski

